version: '3.9'

networks:
  dataprovider_default:
    driver: bridge
    external: true

services:
  db:
    hostname: db
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=dataproviderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5431:5431"
    networks:
      - dataprovider_default

  web:
    container_name: web
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dataproviderdb
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dataprovider_default

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
    networks:
      - dataprovider_default

  celery:
    container_name: celery
    image: celery
    restart: always
    build:
      context: .
    command: celery -A DataProvider worker -l info -B
    environment:
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - web
      - rabbitmq
      - db
    networks:
      - dataprovider_default
